--- Trigger for CLIENT table

CREATE TABLE CLIENTCHECK(
	NEW_NAME varchar2(30),
	OLD_NAME varchar2(30),
	USER_NAME varchar2(30),
	ENTERY_DATE varchar2(30),
	operation varchar2(30)
);


set serveroutput on
CREATE OR REPLACE TRIGGER CHECKTRIGGER
BEFORE INSERT OR DELETE OR UPDATE ON CLIENT
FOR EACH ROW  

BEGIN

  IF INSERTING THEN
  INSERT INTO CLIENTCHECK (NEW_NAME, OLD_NAME, USER_NAME, ENTERY_DATE, operation) VALUES(:NEW.NAME, Null, 'USER', TO_CHAR(sysdate, 'DD/MON/YYYY HH24:MI:SS'), 'INSERT');
  ELSIF DELETING THEN
  INSERT INTO CLIENTCHECK (NEW_NAME, OLD_NAME, USER_NAME, ENTERY_DATE, operation) VALUES(NULL, :OLD.NAME, 'USER', TO_CHAR(sysdate, 'DD/MON/YYYY HH24:MI:SS'), 'DELETE');
  ELSIF UPDATING THEN
  INSERT INTO CLIENTCHECK (NEW_NAME, OLD_NAME, USER_NAME, ENTERY_DATE, operation) VALUES(:NEW.NAME, :OLD.NAME, 'USER', TO_CHAR(sysdate, 'DD/MON/YYYY HH24:MI:SS'), 'UPDATE');
  END IF;
END;
/

--SHOW ERRORS;



